# Generated by Django 3.2.6 on 2022-03-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='photo',
            field=models.ImageField(default='media/contest.jpg', upload_to='voteDeck_contest'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='photo',
            field=models.ImageField(default='media/contestant.jpg', upload_to='voteDeck_contestant'),
        ),
    ]
